FROM python:3.11-slim

WORKDIR /app
COPY ./api /app/api
COPY requirements.txt /app/

RUN pip install --no-cache-dir -r requirements.txt

CMD ["uvicorn", "api.app:app", "--host", "0.0.0.0", "--port", "8080"]
