FROM python:3.11-slim

WORKDIR /app
COPY ./ui /app/ui
COPY requirements.txt /app/

RUN pip install --no-cache-dir -r requirements.txt

CMD ["streamlit", "run", "ui/app.py", "--server.port=8501", "--server.address=0.0.0.0"]
