version: "3.9"
services:
  redis:
    image: redis:7-alpine
    env_file: .env
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file: .env
    environment:
      - REDIS_URL=redis://redis:6379/0
    ports:
      - "8080:8080"
    depends_on:
      - redis

  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    env_file: .env
    environment:
      - API_URL=http://api:8080
    ports:
      - "8501:8501"
    depends_on:
      - api
