version: "3.9"

services:
  web:
    build: .
    container_name: fastapi_long_running_jobs_app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - redis

  worker:
    build: .
    container_name: celery_worker
    command: celery -A app.core.celery_app.celery_app worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: redis_broker
    ports:
      - "6379:6379"
